<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'category_id'     => 1,
                'name'            => 'Panigale V4 S',
                'slug'            => 'panigale-v4-s',
                'description'     => 'Panigale V4 S adalah puncak teknologi superbike Ducati. Mesin Desmosedici Stradale 1103cc langsung dari MotoGP memberikan 215.5 HP yang luar biasa. Dilengkapi suspensi Ohlins NIX30 dan TTX36, serta elektronik MotoGP-derived terlengkap di kelasnya.',
                'price'           => 999000000,
                'stock'           => 3,
                'image_url'       => 'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?w=800&q=80',
                'engine_cc'       => 1103,
                'power_hp'        => 215,
                'credit_eligible' => true,
                'created_at'      => Carbon::now(),
                'updated_at'      => Carbon::now(),
            ],
            [
                'category_id'     => 1,
                'name'            => 'Panigale V2',
                'slug'            => 'panigale-v2',
                'description'     => 'Panigale V2 menghadirkan DNA superbike sesungguhnya dengan mesin SuperQuadro 955cc yang menghasilkan 155 HP. Desain aerodinamis yang terinspirasi MotoGP menjadikannya pilihan sempurna di lintasan maupun jalan raya.',
                'price'           => 599000000,
                'stock'           => 5,
                'image_url'       => 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
                'engine_cc'       => 955,
                'power_hp'        => 155,
                'credit_eligible' => true,
                'created_at'      => Carbon::now(),
                'updated_at'      => Carbon::now(),
            ],
            [
                'category_id'     => 1,
                'name'            => 'Panigale V4 R',
                'slug'            => 'panigale-v4-r',
                'description'     => 'Panigale V4 R adalah motor homologasi untuk WorldSBK. Mesin 998cc menghasilkan 221 HP dalam versi standar, dan bisa mencapai 240 HP dengan kit balap. Motor paling ekstrem yang bisa dikendarai di jalan raya.',
                'price'           => 1499000000,
                'stock'           => 1,
                'image_url'       => 'https://images.unsplash.com/photo-1609630875171-b1321377ee65?w=800&q=80',
                'engine_cc'       => 998,
                'power_hp'        => 221,
                'credit_eligible' => true,
                'created_at'      => Carbon::now(),
                'updated_at'      => Carbon::now(),
            ],

            [
                'category_id'     => 2,
                'name'            => 'Monster SP',
                'slug'            => 'monster-sp',
                'description'     => 'Monster SP adalah versi paling sporty dari Monster terbaru. Mesin Testastretta 937cc menghasilkan 111 HP dengan bobot hanya 188kg. Suspensi Ohlins dan rem Brembo Stylema menjadikannya raja jalanan.',
                'price'           => 385000000,
                'stock'           => 8,
                'image_url'       => 'https://images.unsplash.com/photo-1449426468159-d96dbf08f19f?w=800&q=80',
                'engine_cc'       => 937,
                'power_hp'        => 111,
                'credit_eligible' => true,
                'created_at'      => Carbon::now(),
                'updated_at'      => Carbon::now(),
            ],
            [
                'category_id'     => 2,
                'name'            => 'Monster Plus',
                'slug'            => 'monster-plus',
                'description'     => 'Monster Plus hadir dengan windscreen dan cover penumpang sebagai standar. Desain ikonik Ducati dalam paket yang lebih praktis untuk penggunaan sehari-hari tanpa mengorbankan performa.',
                'price'           => 299000000,
                'stock'           => 10,
                'image_url'       => 'https://images.unsplash.com/photo-1571008887538-b36bb32f4571?w=800&q=80',
                'engine_cc'       => 937,
                'power_hp'        => 111,
                'credit_eligible' => true,
                'created_at'      => Carbon::now(),
                'updated_at'      => Carbon::now(),
            ],

            [
                'category_id'     => 3,
                'name'            => 'Multistrada V4 S',
                'slug'            => 'multistrada-v4-s',
                'description'     => 'Multistrada V4 S adalah motor adventure paling canggih di dunia. Radar depan dan belakang untuk blind spot detection, suspensi semi-aktif Skyhook, dan mesin V4 170 HP menjadikannya motor perjalanan terbaik yang pernah ada.',
                'price'           => 899000000,
                'stock'           => 4,
                'image_url'       => 'https://images.unsplash.com/photo-1449426468159-d96dbf08f19f?w=800&q=80',
                'engine_cc'       => 1158,
                'power_hp'        => 170,
                'credit_eligible' => true,
                'created_at'      => Carbon::now(),
                'updated_at'      => Carbon::now(),
            ],
            [
                'category_id'     => 3,
                'name'            => 'Multistrada V2',
                'slug'            => 'multistrada-v2',
                'description'     => 'Multistrada V2 menghadirkan fleksibilitas tur jarak jauh dengan mesin SuperQuadro Mono 937cc. Empat riding mode dan elektronik lengkap membuatnya adaptif di berbagai kondisi jalan.',
                'price'           => 549000000,
                'stock'           => 6,
                'image_url'       => 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
                'engine_cc'       => 937,
                'power_hp'        => 113,
                'credit_eligible' => true,
                'created_at'      => Carbon::now(),
                'updated_at'      => Carbon::now(),
            ],

            [
                'category_id'     => 4,
                'name'            => 'Scrambler Icon',
                'slug'            => 'scrambler-icon',
                'description'     => 'Scrambler Icon adalah interpretasi modern dari motor scrambler klasik. Mesin L-twin 803cc yang torsy dan mudah dikendarai, dibalut desain retro yang timeless. Motor paling accessible dalam lineup Ducati.',
                'price'           => 219000000,
                'stock'           => 12,
                'image_url'       => 'https://images.unsplash.com/photo-1609630875171-b1321377ee65?w=800&q=80',
                'engine_cc'       => 803,
                'power_hp'        => 73,
                'credit_eligible' => true,
                'created_at'      => Carbon::now(),
                'updated_at'      => Carbon::now(),
            ],
            [
                'category_id'     => 4,
                'name'            => 'Scrambler Full Throttle',
                'slug'            => 'scrambler-full-throttle',
                'description'     => 'Scrambler Full Throttle terinspirasi oleh flat track racing. Handlebar flat, pelek spoked khusus, dan livery khas balap menciptakan karakter unik yang membedakannya dari scrambler manapun.',
                'price'           => 259000000,
                'stock'           => 7,
                'image_url'       => 'https://images.unsplash.com/photo-1571008887538-b36bb32f4571?w=800&q=80',
                'engine_cc'       => 803,
                'power_hp'        => 73,
                'credit_eligible' => true,
                'created_at'      => Carbon::now(),
                'updated_at'      => Carbon::now(),
            ],

            [
                'category_id'     => 5,
                'name'            => 'Streetfighter V4 S',
                'slug'            => 'streetfighter-v4-s',
                'description'     => 'Streetfighter V4 S adalah Panigale V4 tanpa fairing — motor paling brutal yang pernah dibuat Ducati. 208 HP, downforce wing, dan elektronik MotoGP dalam wujud naked yang mengerikan namun memesona.',
                'price'           => 849000000,
                'stock'           => 3,
                'image_url'       => 'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?w=800&q=80',
                'engine_cc'       => 1103,
                'power_hp'        => 208,
                'credit_eligible' => true,
                'created_at'      => Carbon::now(),
                'updated_at'      => Carbon::now(),
            ],
            [
                'category_id'     => 5,
                'name'            => 'Streetfighter V2',
                'slug'            => 'streetfighter-v2',
                'description'     => 'Streetfighter V2 menggabungkan mesin Panigale V2 dengan posisi berkendara naked yang lebih ergonomis. 155 HP dalam paket yang lebih lincah dan agresif untuk pemakaian harian.',
                'price'           => 549000000,
                'stock'           => 5,
                'image_url'       => 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
                'engine_cc'       => 955,
                'power_hp'        => 155,
                'credit_eligible' => true,
                'created_at'      => Carbon::now(),
                'updated_at'      => Carbon::now(),
            ],

            [
                'category_id'     => 6,
                'name'            => 'Diavel V4',
                'slug'            => 'diavel-v4',
                'description'     => 'Diavel V4 adalah power cruiser paling mewah Ducati. Mesin V4 Granturismo 1158cc menghasilkan 168 HP dengan torsi berlimpah di seluruh rentang putaran. Desain futuristik yang memadukan kemewahan dengan performa brutal.',
                'price'           => 749000000,
                'stock'           => 4,
                'image_url'       => 'https://images.unsplash.com/photo-1609630875171-b1321377ee65?w=800&q=80',
                'engine_cc'       => 1158,
                'power_hp'        => 168,
                'credit_eligible' => true,
                'created_at'      => Carbon::now(),
                'updated_at'      => Carbon::now(),
            ],
        ]);
    }
}
